name: Build and Publish Docker Image

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the build on (e.g., main or master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout

    # Log in to GitHub Container Registry (GHCR)
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Build the Docker image
    - name: Build the Docker image
      run: docker build -t ghcr.io/${{ github.repository }}:latest .

    # Push the Docker image to GHCR
    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository }}:latest

    # (Optional) Tag with Git commit SHA
    - name: Tag and Push image with Git SHA
      run: |
        IMAGE_TAG=ghcr.io/${{ github.repository }}:${{ github.sha }}
        docker tag ghcr.io/${{ github.repository }}:latest $IMAGE_TAG
        docker push $IMAGE_TAG
